import type React from "react"
import {
	IconFileText,
	IconPhoto,
	IconVideo,
	IconMusic,
	IconFileZip,
	IconDatabase,
	IconSearch,
	IconBrandGithub,
	IconSun,
	IconMoon,
	IconScissors,
	IconSettings,
	IconDownload,
	IconTrash,
	IconArrowRight,
	IconPlus,
	IconMaximize,
	IconMinimize,
	IconRotate,
	IconCrop,
	IconArrowAutofitHeight,
	IconArrowAutofitWidth,
	IconDroplet,
	IconGrid4x4,
	IconFileFilled,
	IconHistory,
	IconX,
	IconCheck,
	IconExternalLink,
	IconAdjustments,
	IconGhost,
	IconTypography,
	IconDownloadOff,
	IconFiles,
	IconFolder,
	IconTerminal2,
	IconTable,
	IconChevronUp,
	IconChevronDown,
	IconPlayerPlay,
} from "@tabler/icons-react"

export const ICON_MAP = {
	pdf: IconFileText,
	image: IconPhoto,
	video: IconVideo,
	audio: IconMusic,
	file: IconFileZip,
	data: IconDatabase,
	document: IconFileFilled,
	search: IconSearch,
	github: IconBrandGithub,
	sun: IconSun,
	moon: IconMoon,
	scissors: IconScissors,
	settings: IconSettings,
	download: IconDownload,
	trash: IconTrash,
	"arrow-right": IconArrowRight,
	plus: IconPlus,
	maximize: IconMaximize,
	minimize: IconMinimize,
	rotate: IconRotate,
	crop: IconCrop,
	height: IconArrowAutofitHeight,
	width: IconArrowAutofitWidth,
	droplet: IconDroplet,
	grid: IconGrid4x4,
	history: IconHistory,
	close: IconX,
	check: IconCheck,
	external: IconExternalLink,
	adjust: IconAdjustments,
	ghost: IconGhost,
	text: IconTypography,
	"download-off": IconDownloadOff,
	files: IconFiles,
	folder: IconFolder,
	terminal: IconTerminal2,
	table: IconTable,
	up: IconChevronUp,
	down: IconChevronDown,
	play: IconPlayerPlay,
} as const

export type IconName = keyof typeof ICON_MAP

interface IconProps extends React.ComponentProps<typeof IconFileText> {
	name: IconName | string
}

export default function Icon({ name, ...props }: IconProps) {
	const IconComponent = ICON_MAP[name as IconName] || IconFileText
	return <IconComponent {...props} />
}
